window.version='1.5';
window.SKSN_BJGS_A={	 
  '前言':{  
    'version':'设定',
        'players':[],
    'info':'<b>前言·起源>>></b><br><br><li>某次时空异变，天空中出现了巨大的漩涡将世物都吸入漩涡中再将其粉碎，不过在其中还有少数人活了下来，他们来到了另一个世界，一个充满生机和神秘的世界，那些存活下来的人都获得了强大的特殊能力，不过这个世界上本身就存在着跟他们一样拥有特殊能力的人，他们一律被称为异能者，为了在这个世界生存他们同他们所在的国家合作，当然也有一些不甘趋于人下者，秘密联合起来，在异界发展自己的势力。<br><br>以下则是目前时空枢纽世界观中的势力分类。',
    'cards':[],
  },
  '雾言联盟':{  
    'version':'简介',
	'players':[],
    'info':'一个由异世界人和反对帝都和教会统治的人组成的一个暗杀组织，首领是提隆•嘉尼奥，奉行无政府主义，目的是推翻教会和帝国的腐朽统治',
    'cards':[],
  },
  '圣光教会':{  
    'version':'简介',
	'players':["sksn_aidehua","sksn_jianiao","sksn_eidehua","sksn_lanbote","sksn_fuleicha"],
    'info':'路西法教的信仰者组建的宗教机构，教会势力遍布西大陆，教皇是实质上的最高宗教领袖',
    'cards':[],
  },
  '宗教审判厅':{  
    'version':'简介',
	'players':["sksn_saimiuer","sksn_ailuoyi"],
    'info':'教皇直属机构，独立于教会体系外，由教会的顶尖战力组成，负责清剿异教徒和对抗特大灾害',
    'cards':[],
  },
  '凯洛亚学院':{  
    'version':'简介',
	'players':[],
    'info':'位于帝都的凯洛亚学院是西大陆的学术中心，这里培养了各个地方的精英学子，以及开发出诸多灵能科技，而教会则对日益壮大的学院派势力深感忧虑',
    'cards':[],
  },
  '长明殿':{  
    'version':'简介',
	'players':["sksn_aodinggelan","sksn_luoyiao","sksn_youliweisi","sksn_sigeruopi"],
    'info':'东极宗教机构，路西法教分支，长明殿由先知斐洛统领，负责维系东极的社会秩序和对抗魔能之地的魔物入侵',
    'cards':[],
  },
  '魔域同盟':{  
    'version':'简介',
	'players':["sksn_feiluo","sksn_pianxian"],
    'info':'由魔能之地四大领主组建，统治着所有魔能之地的魔兽和魔人，盟主是莽血魔王奥克佩特，目的是突破飞云渡，统治东大陆。',
    'cards':[],
  },
  '地下世界':{  
    'version':'简介',
	'players':["sksn_occupatee","sksn_jiamiu","sksn_gaozesi","sksn_zage"],
    'info':'与明面上的世界不同，地下世界由各帝国实权人物和精英组成，他们控制着国家的经济和绝大部分黑市交易，在暗处统治着世界',
    'cards':[],
  },
  '冒险者协会':{  
    'version':'简介',
	'players':["sksn_wulamu","sksn_mogen","sksn_maisike","sksn_guergewen"],
    'info':'本部坐落于荒芜疆土天涯城，冒险者协会为冒险者提供情报和任务，探查遗迹或消灭魔物，接受国家和团体的委托，在世界各地都有分布。',
    'cards':[],
  },
  '黎明阵线':{  
    'version':'简介',
	'players':["sksn_deyingkemeng","sksn_xiayi","sksn_ying"],
    'info':'以东极科恩城为根据地的军政联合体，继承了雅各布的学说思想，主张解放亚人，废除帝制，联合群众建立一个人人平等的新国家',
    'cards':[],
  },
  '裂序之权':{  
    'version':'简介',
	'players':["sksn_dongfanghongdao","sksn_nuoya","sksn_lujinuo","sksn_yunru","sksn_muguchen","sksn_yilian"],
    'info':'伊凡帝勒为了巩固自己的统治所建立的以其为尊的组织，以便管理统治区内的各项事务，其成员大多是异教徒及亡命之徒。',
    'cards':[],
  },
  '<font color=slategrey>虚无教派</font>':{  
    'version':'简介',
	'players':["sksn_ferwork"],
    'info':'由几位虚无代行者组建的松散联盟，通过搅动世界的局势来为虚无的降临创造条件。',
    'cards':[],
  },
  '<font color=cyan>时空圣殿</font>':{  
    'version':'简介',
	'players':["sksn_siji","sksn_guiyan","sksn_hualun"],
    'info':'维护着时空的平衡，同时降下神谕指引各个世界的凡人，一共拥有八位管理者以及一位最高统治者。',
    'cards':[],
  },
  '敬请期待':{  
    'version':'暂无',
	'players':["sksn_halidisi","sksn_jielaer","sksn_niepudun","sksn_nuodengsi","sksn_you"],
    'info':'暂无',
    'cards':[],
  },
  /*'模板':{  
    'version':'简介',
	'players':["sksn_xxx"],
    'info':'背景描述',
    'cards':[],
  },*/
  
  
  
			   
  
}